### ISSUE TITLE
A solution for the request from Khaled Shahin

### ISSUE THREAD

**Issue by terrygibbs** [sillsdev/SpeechAnalyzer#107]
Hi,

From his request:
https://community.software.sil.org/t/adding-a-file-information-for-f2-f1-acoustic-space/6688

Khaled_Shahin wrote,
"Is it possible to add a file information that contains a custom F2-F1 space for another language
than those listed by default in Speech analyzer? Arabic for instance.

--------------
Solution:

On December 27 I began to talk with Micah MacLean about working on this problem.

He and I have both spent considerable time trying to fix this.
The good news is that yesterday, he was able to find a solution to this complex problem.

In the past 2 days Micah has written:

It's been a month since I updated you on Speech Analyzer. I got the ocx file working and was looking into the building script. I wasn't sure how to edit the script because it looked like it was generated by some program. Another option would be to add the ocx file to the list of dependencies that a user needs to download.

===

I've received most of the files you sent.
With the ocx file now working I'm happy to update the guides on git to mention it and walk a user through registering the ocx file which allows the user to see the menu.

===

Currently, it looks like it will allow a user to edit any configuration for formants, either the preset or the custom ones without pressing any keys.

===

My questions is, is it ok for Micah to send the OCX file to Darcy and have Micah explain to him how to install it?

Also, do I need to upload any of the email's that were sent between Micah and myself?

Thanks,

Terry

**Comment by darcywong00** [comment]
> I've received most of the files you sent.
With the ocx file now working I'm happy to update the guides on git to mention it and walk a user through registering the ocx file which allows the user to see the menu.

@micahtmaclean - go ahead and create a PR to update the guides and what you did. Thanks

**Comment by micahtmaclean** [comment]
@darcywong00 I have updated the Dev guide. I wasn't sure if you wanted me to write a guide for users. The steps to register the ocx would be identical.
