### ISSUE TITLE
Ensure Inno Installer creation references NuGet dependencies

### ISSUE THREAD

**Issue by megahirt** [sillsdev/SpeechAnalyzer#12]
We need to ensure that the Inno Installer creation process will include the xerces-c NuGet dependency.  See https://github.com/sillsdev/SpeechAnalyzer/pull/11#issuecomment-856537785

**Comment by darcywong00** [comment]
Adding a note. When we get to updating `/Install/SpeechAnalyzer.iss`, we can update 

`#define myAppURL` to  `"https://software.sil.org/speech-analyzer/"`

**Comment by darcywong00** [comment]
Fixed by #21
