### ISSUE TITLE
feat: Use langtags.json file

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/SpeechAnalyzer#14]
> When the lift file is generated, the language tags don't seem to be BCP-47 so Flex treats the writing systems differently

This is likely gonna be a big hurdle. Unfortunately, I don't think we can drop in 
https://github.com/sillsdev/libpalaso/tree/master/SIL.WritingSystems

Wonder if we parse the langtags.json file from https://github.com/silnrsi/langtags/ for SA's language list...

_Originally posted by @darcywong00 in https://github.com/sillsdev/SpeechAnalyzer/issues/2#issuecomment-855774828_

**Comment by megahirt** [comment]
I would suggest writing a one-off script to generate a pipe-delimited language file in the format that SA expects, and generate that from the latest langtags.json file.  This would in theory update SA with the latest language tag information while leaving the existing functionality (even if it's lacking or just plain wrong) intact.  A separate issue could be to re-engineer how language tags are picked.  This is a thing in SIL - a proper language picker in all of its complexity.  Like you said - likely a big hurdle.
