### ISSUE TITLE
chore: Get unit tests working

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/SpeechAnalyzer#15]
@megahirt noticed there's several unit test projects that aren't automatically built & run.

Using VS 2019's Test Explorer, we should
* get an inventory of what unit tests pass / fail
* develop a GitHub action to automate running tests

**Comment by megahirt** [comment]
Some documentation on using VS Test Explorer: https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019

**Comment by megahirt** [comment]
Some documentation on running unit tests from the command line and using Github Actions:

https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019

https://www.tessapower.co/github-actions/

**Comment by darcywong00** [comment]
Documenting the state of unit tests as of the latest `master` branch:


## ElanUtilsTest
0/1 test pass

## LiftUtilsTest
6/7 tests pass (LiftSimple_04 fails)

## SAScriptingTest
0/29 tests pass

## URIParserTest
58/58 tests pass

## WaveUtilsTest
### WaveReadTest
0/4 tests pass

### WaveResampleTest
0/13 tests run (nothing happens?)

### WaveWriteTest
1/4 tests pass

**Comment by darcywong00** [comment]
The unit tests are passing with #22.
The GitHub action to run unit tests is in development with #20

**Comment by darcywong00** [comment]
@megahirt - Your two PR's above resolve this issue, right?

**Comment by megahirt** [comment]
I think we can call this done.
