### ISSUE TITLE
Chore: merge duplicate release notes / changelog into changelog

### ISSUE THREAD

**Issue by megahirt** [sillsdev/SpeechAnalyzer#32]
SA has two files which contain duplicate release notes.  We should only have one file that needs updating upon release.  I would advocate for just the changelog.md but we need to understand where `release notes.txt` is used in the application or also on other websites.

**Comment by darcywong00** [comment]
Some notes:

The Speech Analyzer download page links to changelog.md
https://software.sil.org/speech-analyzer/#downloads

The Speech Analyzer help menu "What's New" opens "release notes.txt".

**Comment by megahirt** [comment]
The current plan I believe is to end up with one file CHANGELOG.md  I think it would be satisfactory to assume the user has internet access and change the **Help -> What's New** link to open an external link to https://github.com/sillsdev/SpeechAnalyzer/blob/master/CHANGELOG.md
