### ISSUE TITLE
bug: Add shortcuts to select next/previous graph

### ISSUE THREAD

**Issue by terrygibbs** [sillsdev/SpeechAnalyzer#37]
Hi,
I now realize that I've miss-understood what Mr. Roussi was saying and what he was asking for.
I heard him say Graph which I interpreted as "The Window" that hold all of the Graphs.
But what he was talking about was the sub-Graphs that are within the main file.
That is, I was thinking that he wants to use Shift+Tab to go from one Graph window to another; like this...
 
![Shift+Tab vx](https://user-images.githubusercontent.com/13848182/131304034-1f2ef196-4c39-482b-b9cd-7900afe04478.jpg)

But what he's thinking is the Shift-Tab feature that provided movement from one Plot window to another to another.
So he is raising a valid point in that the current Shift-Tab function is completely incorrect.
As I noted previously, in 2018 these 2 Key sequences were changed...
        -Modified shortcut keys for Shift-Tab and Alt-Tab.
           . Alt-Tab has been removed from usage.
           . Shift-Tab now selects the previous segment.
I don't remember why Alt+Tab was removed from usage.
It currently causes SA to show files on the desktop; which is of no use to us.
The Shift-Tab feature was changed to provide the convention of using tabs to move left and right: Tab and Shift+Tab.
Making this change broke the "Select a new active graph.  Shift+Tab" feature, which never got fixed.
Since Tab and Shift+Tab have been in use for such a long time, I suggest they be left as is.
I suggest leaving the "Select another file (if open).  Ctrl+Tab" feature as is since it will Tab to a new open file with-in SA.
Since there is currently no way to move between multiples Graphs in a single file, as Mr. Roussi is asking for, it seems reasonable to "fix" this issue someday.
Since Alt+Tab is not useful, I suggest connecting it instead to the Active Graph windows code that already exists, and as a result it will become the way to move between multiples Graph. 
Since Shift+Tab is not currently working for his use, his only choice it to use the mouse to select a sub-window.
I have no idea how high a priority this should be, since it may be in little use now-a-days.

Sorry for not figuring all of this out sooner,
Terry

**Comment by darcywong00** [comment]
Initial discussion at
https://community.software.sil.org/t/shift-tab-shortcut-does-not-work-in-the-latest-version-3-1-1-1-of-speech-analyzer/5232

I think we want to merge #38 into this

**Comment by darcywong00** [comment]
In a PM, the community site user approves using Ctrl and Down/Up

> That would be great! Better than Shift+Tab.
