### ISSUE TITLE
locate chm help file source and develop help file compile step

### ISSUE THREAD

**Issue by megahirt** [sillsdev/SpeechAnalyzer#41]
At this point we don't know where the original help files are, as they seem to be absent from the repo.

The main chm help file is https://github.com/sillsdev/SpeechAnalyzer/blob/master/DistFiles/Speech_Analyzer_Help.chm

**Comment by megahirt** [comment]
@terrygibbs do you know where the help file source is for the chm ?

**Comment by darcywong00** [comment]
TODO
- [ ] Document shortcut keys from #39 of <kbd>Ctrl</kbd>+<kbd>Down</kbd> and <kbd>Ctrl</kbd>+<kbd>Up</kbd> to select next/previous graph

**Comment by megahirt** [comment]
We'll keep this issue open until we find the source HTML or we give up looking.

**Comment by megahirt** [comment]
If we cannot locate the source, we may decide to decompile the CHM files and try to re-build a modified CHM.  Here are some methods for decompiling CHM https://www.help-info.de/kb/en/HTMLHelp/100007-hh-decompile-chm.html

**Comment by darcywong00** [comment]
I've managed to convert the chm file to one big Markdown file. My plan is to split those into folders, and then we can use pandoc to convert the Markdown to a chm file.

The Keyman team already uses this workflow to generate in-app help.

**Comment by megahirt** [comment]
this sounds great!  Love that we can capitalize on the way Keyman help is already working.
