### ISSUE TITLE
bug: Error on "Save As" with mp3 file

### ISSUE THREAD

**Issue by megahirt** [sillsdev/SpeechAnalyzer#49]
There's not yet enough information here to reproduce, but I'm creating an issue here to track this post.

https://community.software.sil.org/t/why-cannot-i-save-my-sa-audio/5380

@terrygibbs can you try and reproduce the error and offer some more explanation in this issue and on the community site?  Thanks.

**Comment by darcywong00** [comment]
My steps to reproduce the error:
1. Rename an mp3 file to use a long name as reported
    https___psv4.userapi.com_c538232__u366021368_audiomsg_d23_a40be394af.mp3
2. In SA, open the mp3 file
3. Then File --> Save As
generates the error prompt

**Comment by darcywong00** [comment]
In discussing with @terrygibbs , he pointed out that SA natively processes wav files. While SA can open mp3 files, it's "read-only", so we should disable "Save As".

To convert from mp3 to wav file, follow the "Paste as New File" steps. I'll add a troubleshooting help file for this in #53

**Comment by kgorham** [comment]
I looked at the code for this problem.  Internally, SA will be working on a temporary .wav file.  When SaveAs is used the code checks to see if it's using a temp .wav file, but the variable for that indicator isn't set - even though the .mp3 has been read in and the tmp .wav file does exists in the document.  So it then decides that it must be a regular wav file and then blindly renames the extension and tries to open the file as a wav (yes, during the saveas). this fails, throws an exception which displays the error.

**Comment by megahirt** [comment]
Nice investigation, Kent!

What do you suggest as the fix?

>

**Comment by kgorham** [comment]
Internally, SA has already created a temporary wav file of the recording.  I think we could just save that.  I will play with that and send a sample of the output.  The user wont have control over the parameters of the wav file (e.g. hz).  It will created according to SAs settings.
As an alternative, maybe there could be an 'Export As', where as 'Save As' implies the original file format is retained, and 'Export As' implies the format will be changed.  Just listing some ideas.  no guarantee they are 'good' ideas.

**Comment by kgorham** [comment]
Capturing email from Terry to Darcy:

> Darcy,
> SA can open a MP3 file, but when a user tries to save the file, then SA shows dialog box like this:
![image](https://user-images.githubusercontent.com/10772332/141304141-6677496c-9d43-4979-b5a9-54137caddc36.png)
> This was by design as of June 2005.
>   . MP3 and WMA support (read-only access).
> > By now there needs to be an obvious way for a user to save MP3 files.
> > My suggestion is to not gray out the "Save As..." option,
> but simply change the content of the popup dialog text above.
![image](https://user-images.githubusercontent.com/10772332/141304200-47472345-e4ea-49ae-9936-8bbf66ba22d2.png)
> > That is, let the user click on the "Save As..." and when the the dialog shows up,
> use this revised text to explain how to handle an MP3 file "Save As..." request.
![image](https://user-images.githubusercontent.com/10772332/141304232-71cbac06-c19f-4e9d-98cc-17e5a24c97ac.png)
> > This will create a .Wav file that SA can now save.
> Terry

**Comment by darcywong00** [comment]
More historical background from @terrygibbs 

> As I have previously noted:
>
>    This was by design as of June 2005.
    . MP3 and WMA support (read-only access).
>
>We wanted to make it a bit difficult for a user to convert an MP3 file because it does not 'fit' the kind of work that SA is designed to work with.
>
>By definition a Wav file generates un-compressed audio data at a bit rate of 1,411 kbit/s
Depending on how the MP3 recorder is configured, an MP3 file will loose from 5 to 10 times that amount of data per second.
>
>MP3 is fine for recording music and listening to music, but the simple fact is that MP3 data is un-usable for Spectrogram and Formant Track use.
>
>It was our experience that people would record their linguistic data in MP3 format and then convert it to Wav and then complain that SA did not accurately render the details they expected when doing their analysis work.
>
>Thus we made it not so straight forward for users to convert MP3 to Wav.
Linguists understand this situation, but novice users often miss this very important issue.

**Comment by kgorham** [comment]
@darcywong00
I tried your download link.  Seemed to run fine. (uninstalled old SA and reinstalled new).
As an improvement, I would suggest stealing some of the code that is in place already, and use the first part of the filename for the new filename instead of using the .tmp filename.
![image](https://user-images.githubusercontent.com/10772332/141876924-65538b0a-3888-4186-b42f-eae9a6cad58e.png)
