### ISSUE TITLE
feat: Request to export CSV

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/SpeechAnalyzer#74]
@sdysart is supporting some users who are converting wordlists from SA into Cog.
Currently, Cog is expecting .csv files in the format:
row 1 - glosses separated by commas
row 2 - secondary field (IPA?)

### Workaround
@sdysart starts with SA exporting to Fieldworks SFM.
Then, he's applying a regex in Notepad++ to create CSV (data in column 1 and column 2).
Then, he's applying a Google sheet transpose to get the data into 2 rows.

**Comment by sdysart** [comment]
Terry G. pointed out that there is an option to export SFM as Rows.  
![image](https://user-images.githubusercontent.com/26537840/159444279-bd252b72-10f7-419e-85e2-b4f3f7b63e9d.png)
which exports as rows with a space separating the entries.
Can we replace the autogenerated space with an autogenerated comma ( , ).  We could then open the output as a csv file and edit as required in excel.

**Comment by megahirt** [comment]
wow, I didn't know about that option, but that would seem to make this task
MUCH easier - thanks Scott and Terry!
