### ISSUE TITLE
bug: Function keys for playback functions

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/SpeechAnalyzer#90]
@terrygibbs reported the following from a user (along with his workaround afterwards)

> The current issue I have is the F keys for playback functions. For example, I set up Ctl-F1 to play at half speed between cursors, and it plays AFTER the right cursor instead. Not a huge deal, but a deal.
>
> Keep plugging!

----

> Sorry to hear about this problem.
>
>I've found if you want to playback a Selection,
then instead of using the "Between Cursors" option,
use instead the next option "Left Window -> Begin Cursor".
>
>Obviously there is a "wiring" problem with what-goes-where.
>
>I hope this helps,
![left window](https://user-images.githubusercontent.com/7358010/204934612-c18a256c-1c7c-4472-8264-f5e2253512d9.png)

**Comment by megahirt** [comment]
Additional context from @terrygibbs on Dec 2:

> Below is some additional new information regarding how to locate the problem.
> 
> The left Red circle is the shortcut button for hearing the playback of what is selected by the 2 cursors.
> It is permanently connected to the "Between Cursors" option that is in the Playback/ Player menu.
> 
> The right Red circle is the shortcut button to the Player itself.
 
![sa2](https://user-images.githubusercontent.com/3444521/207252405-c85054ea-e067-4534-8d80-90990e28c7a6.png)

> If you click the red "Between Cursors" button above, you will hear the audio that is between the 2 cursors.
> 
> If you click the red "Player" button on the right you will see that "Between Cursors" is selected.
![sa3](https://user-images.githubusercontent.com/3444521/207252585-6d78717e-36aa-4dde-ac86-4eef0f2623b7.png)

> If you also show the "Function Keys Setup" item you will see that F1 is connected to "Between Cursors".
![sa4](https://user-images.githubusercontent.com/3444521/207252674-c34608de-100c-4a91-9847-004333355645.png)

> 
> The basic problem is that the if you close the "Function Keys Setup" and Player, and the select the menu item
> Playback, and then select "Function Keys" and Ctrl+F1 then you will not not get the audio from between the
> 2 cursors, but instead you will get audio that starts at the Red Cursor and plays to the end of the file.
> 
> If you want to hear the correct Audio that is between the 2 cursors, you must select the menu item Playback,
> and then select "Function Keys" and Ctrl+F2

![sa5](https://user-images.githubusercontent.com/3444521/207252738-3ab23b88-055c-427c-9a71-209a09a29198.png)

> This is a single example of playback not being "connected" correctly.
> In fact all of the items in the "Function Keys" list are in an incorrect  location.
